spring:
  config:
    activate:
      on-profile: local
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bleu_auction_db
    username: root
    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://db-isp7r-kr.vpc-pub-cdb.ntruss.com:3306/bleuauction
#    username: bleuauction
#    password: bleuauction123!@#


  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
      show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

ncp:
  endPoint: https://kr.object.ncloudstorage.com
  regionName: kr-standard
  accessKey: A3YFyEA5Ulxf3Lw71ZQs
  secretKey: d7dSoeeIhZP3P0mTx6syycp0rZ8IVIzTkUz523aTncp
  bucket:
    name: bleuauction-bucket
    paths:
      member: member/
      menu: menu/
      store: store/
      notice: notice/
      review: review/




server:
  port: 8080
  shutdown: graceful
