spring:
  config:
    activate:
      on-profile: local
  devtools:
    livereload:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-isp7r-kr.vpc-pub-cdb.ntruss.com:3306/bleuauction
    username: bleuauction
    password: bleuauction123!@#

server:
  port: 8080
  shutdown: graceful

jpa:
  show-sql: true
  properties:
    hibernate:
      format_sql: true
      default_batch_fetch_size: 100
      dialect: org.hibernate.dialect.MySQLDialect

